### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [shenzekun/vue-qq-music#4]
Hi @shenzekun . I'm a graphic designer and an open source enthusiast. I would like to contribute to your awesome project by proposing a logo/icon design. I'll be doing it as a gift for free to your awesome project.
If you need anything change please let me know,
![vue](https://user-images.githubusercontent.com/36124339/43409109-383b72d0-944d-11e8-83a5-443f439904f3.png)

Best regard.
Mirza Zulfan.

**Comment by shenzekun** [comment]
wow,perfect,thanks:)

**Comment by mirzazulfan** [comment]
Thanks for your response,, i'll send you files and pr.
